#!/bin/bash

set -euo pipefail

repo_dir=$(git rev-parse --show-toplevel)
name=$(basename $repo_dir)-test

docker build -t $name $repo_dir/test

docker run \
    --name $name \
    --rm \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    $( [ -z "$AWS_SESSION_TOKEN" ] || echo "-e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" ) \
    -i $(tty -s && echo -t) \
    -w $repo_dir \
    -v $repo_dir:$repo_dir \
    $name \
        py.test \
        --tb=short \
        "$@"
